# Generated by Django 3.2.19 on 2023-05-31 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagtype',
            name='recipient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recipients.institution', verbose_name='instituição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinetype',
            name='recipient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recipients.institution', verbose_name='instituição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bagtype',
            name='capacity',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='capacidade'),
        ),
        migrations.AlterField(
            model_name='medicinetype',
            name='risk_factor',
            field=models.BooleanField(verbose_name='fator de risco'),
        ),
    ]
