# Generated by Django 3.2.19 on 2023-06-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_id', models.CharField(max_length=50, verbose_name='identificação da bolsa')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=50, verbose_name='tipo sanguíneo')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='quantidade')),
                ('expiry_date', models.DateField(verbose_name='data de validade')),
                ('validation_date', models.DateTimeField(verbose_name='data de validação')),
            ],
            options={
                'verbose_name': 'doação de sangue',
                'verbose_name_plural': 'doações de sangue',
            },
        ),
        migrations.CreateModel(
            name='DonationAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(choices=[('MED', 'Medicamento'), ('SAN', 'Sangue')], max_length=50, verbose_name='tipo de doação')),
                ('scheduled_date', models.DateTimeField(verbose_name='data agendada')),
            ],
            options={
                'verbose_name': 'agendamento de doação',
                'verbose_name_plural': 'agendamentos de doação',
            },
        ),
        migrations.CreateModel(
            name='MedicineDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('compounded', models.BooleanField(default=False, verbose_name='manipulado')),
                ('value', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='valor')),
                ('expiry_date', models.DateField(verbose_name='data de validade')),
                ('validation_date', models.DateTimeField(verbose_name='data de validação')),
            ],
            options={
                'verbose_name': 'doação de medicamento',
                'verbose_name_plural': 'doações de medicamento',
            },
        ),
    ]
