# Generated by Django 3.2.19 on 2023-06-07 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinedonation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='doador'),
        ),
        migrations.AddField(
            model_name='medicinedonation',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipients.medicinetype', verbose_name='medicamento'),
        ),
        migrations.AddField(
            model_name='medicinedonation',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipients.institution', verbose_name='instituição'),
        ),
        migrations.AddField(
            model_name='donationappointment',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='doador'),
        ),
        migrations.AddField(
            model_name='donationappointment',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipients.institution', verbose_name='instituição'),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='bag_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipients.bagtype', verbose_name='doador'),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='doador'),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipients.institution', verbose_name='instituição'),
        ),
    ]
