# Generated by Django 3.2.19 on 2023-05-31 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0002_auto_20230531_1433'),
        ('donations', '0002_auto_20230508_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonation',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipients.institution', verbose_name='instituição'),
        ),
        migrations.AlterField(
            model_name='donationappointment',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipients.institution', verbose_name='instituição'),
        ),
        migrations.AlterField(
            model_name='medicinedonation',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipients.institution', verbose_name='instituição'),
        ),
    ]
